sonar.projectKey=zpp_logs
sonar.sources=zpp_logs
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=report.xml
sonar.junit.reportPaths=report.xml
sonar.python.version=3